spring.application.name=rest-ms
server.servlet.context-path=/api/v1
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:}

app.keycloak.base-url=${KEYCLOAK_BASE_URL:}
app.keycloak.realm=${KEYCLOAK_REALM:}
app.keycloak.client-id=${KEYCLOAK_CLIENT_ID:}
app.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:}
app.keycloak.admin-username=${KEYCLOAK_ADMIN_USERNAME:}
app.keycloak.admin-password=${KEYCLOAK_ADMIN_PASSWORD:}

management.endpoints.web.exposure.include=health,info
